// Comprehensive Dataset of 105+ Curated YouTube Videos for PathSeeker Multimedia Hub
// Categories: current affairs, technology, software development, cybersecurity, graphic design, AI/ML, job market/hiring trends

export const CATEGORIES = [
  'Current Affairs',
  'Technology',
  'Software Development',
  'Cybersecurity',
  'Graphic Design',
  'AI & Machine Learning',
  'Job Market & Hiring Trends',
];

export const YOUTUBE_VIDEO_DATASET = [
  // ── 1. CURRENT AFFAIRS (15 videos) ──────────────────────────────────────────
  {
    youtubeVideoId: 'zOjov-2OZ0E',
    title: 'Global Tech Industry Economic Outlook & Work Trends 2025',
    category: 'Current Affairs',
    description: 'Comprehensive analysis of current economic shifts, tech hiring policies, and global industry trends.',
    thumbnail: 'https://i.ytimg.com/vi/zOjov-2OZ0E/hqdefault.jpg',
    channelTitle: 'Tech Economy Insights',
    duration: '18:40',
    tags: ['Economics', 'Tech News', 'Global Hiring', 'Trends'],
  },
  {
    youtubeVideoId: 'ua-CiDNNj30',
    title: 'The Future of Remote Work & Distributed Teams in 2025',
    category: 'Current Affairs',
    description: 'Examining remote work policies, hybrid models, and global talent acquisition strategies.',
    thumbnail: 'https://i.ytimg.com/vi/ua-CiDNNj30/hqdefault.jpg',
    channelTitle: 'Workforce Today',
    duration: '22:15',
    tags: ['Remote Work', 'Global Talent', 'Workplace Culture'],
  },
  {
    youtubeVideoId: 'J69-q4eLsYU',
    title: 'Silicon Valley & Global Tech Hub Hiring Policy Updates',
    category: 'Current Affairs',
    description: 'Latest news on tech layoffs, hiring rebounds, and visa regulations impacting global engineers.',
    thumbnail: 'https://i.ytimg.com/vi/J69-q4eLsYU/hqdefault.jpg',
    channelTitle: 'Silicon Valley Report',
    duration: '15:30',
    tags: ['Silicon Valley', 'Immigration', 'Hiring Policy'],
  },
  {
    youtubeVideoId: 'vLsVkgngKDQ',
    title: 'AI Regulation Legislation & Ethics in the Workforce',
    category: 'Current Affairs',
    description: 'How EU and US AI laws are impacting tech companies, data privacy, and workplace automation.',
    thumbnail: 'https://i.ytimg.com/vi/vLsVkgngKDQ/hqdefault.jpg',
    channelTitle: 'Tech Law Today',
    duration: '25:10',
    tags: ['AI Ethics', 'Regulation', 'Tech Law'],
  },
  {
    youtubeVideoId: 'grEKMHGYyns',
    title: 'Green Tech & Sustainable Energy Computing Trends',
    category: 'Current Affairs',
    description: 'The rise of sustainable data centers, green cloud engineering, and renewable energy tech roles.',
    thumbnail: 'https://i.ytimg.com/vi/grEKMHGYyns/hqdefault.jpg',
    channelTitle: 'CleanTech World',
    duration: '19:45',
    tags: ['Green Tech', 'Cloud', 'Sustainability'],
  },
  {
    youtubeVideoId: '0GypdsJQN4',
    title: 'Tech Companies Restructuring: What Candidates Need to Know',
    category: 'Current Affairs',
    description: 'How corporate restructuring in 2025 creates new opportunities in specialized technical domains.',
    thumbnail: 'https://i.ytimg.com/vi/0GypdsJQN4/hqdefault.jpg',
    channelTitle: 'Career Strategy Hub',
    duration: '14:20',
    tags: ['Restructuring', 'Hiring', 'Strategy'],
  },
  {
    youtubeVideoId: 'u72H_4c2dGg',
    title: 'Global Semiconductor & Hardware Supply Chain Report',
    category: 'Current Affairs',
    description: 'Current affairs on microchip manufacturing, GPU shortages, and global hardware innovation.',
    thumbnail: 'https://i.ytimg.com/vi/u72H_4c2dGg/hqdefault.jpg',
    channelTitle: 'Hardware Insider',
    duration: '21:00',
    tags: ['Semiconductors', 'Hardware', 'Supply Chain'],
  },
  {
    youtubeVideoId: 'X3paOmcrTjQ',
    title: 'Quantum Computing Breakthroughs & Commercial Readiness',
    category: 'Current Affairs',
    description: 'State of quantum hardware, cryptography changes, and quantum software engineering outlook.',
    thumbnail: 'https://i.ytimg.com/vi/X3paOmcrTjQ/hqdefault.jpg',
    channelTitle: 'Quantum Tech Daily',
    duration: '28:10',
    tags: ['Quantum', 'Physics', 'Deep Tech'],
  },
  {
    youtubeVideoId: '47d_v6S59C0',
    title: 'Tech Venture Capital & Startup Funding Landscape 2025',
    category: 'Current Affairs',
    description: 'Where VC money is flowing: AI startups, cybersecurity, SaaS, and biotech funding trends.',
    thumbnail: 'https://i.ytimg.com/vi/47d_v6S59C0/hqdefault.jpg',
    channelTitle: 'VC Breakdown',
    duration: '17:35',
    tags: ['Venture Capital', 'Startups', 'Funding'],
  },
  {
    youtubeVideoId: 'c9Wg6Cb_YlU',
    title: 'The Shift Towards Skill-Based Hiring vs Traditional Degrees',
    category: 'Current Affairs',
    description: 'Current hiring trends showing top employers dropping degree requirements in favor of proven skills.',
    thumbnail: 'https://i.ytimg.com/vi/c9Wg6Cb_YlU/hqdefault.jpg',
    channelTitle: 'Future of Education',
    duration: '16:50',
    tags: ['Education', 'Skill Based', 'Hiring'],
  },
  {
    youtubeVideoId: 'bJzb-RuUcMU',
    title: 'Digital Sovereignty & Data Residency Laws Worldwide',
    category: 'Current Affairs',
    description: 'Analysis of national cloud sovereignty mandates and their impact on global tech infrastructure.',
    thumbnail: 'https://i.ytimg.com/vi/bJzb-RuUcMU/hqdefault.jpg',
    channelTitle: 'Global Governance Tech',
    duration: '20:15',
    tags: ['Data Sovereignty', 'Cloud', 'Compliance'],
  },
  {
    youtubeVideoId: 'SqcY0GlETPk',
    title: 'Rise of AI-Assisted Workflows in Fortune 500 Enterprises',
    category: 'Current Affairs',
    description: 'How corporate enterprises are deploying internal Copilots and GenAI productivity suites.',
    thumbnail: 'https://i.ytimg.com/vi/SqcY0GlETPk/hqdefault.jpg',
    channelTitle: 'Enterprise Tech Insights',
    duration: '24:00',
    tags: ['Enterprise AI', 'Productivity', 'Digital Transformation'],
  },
  {
    youtubeVideoId: 'fN1Cyr0ZK9M',
    title: 'Cyber Warfare & Geopolitical IT Infrastructure Defense',
    category: 'Current Affairs',
    description: 'National defense technology trends, critical infrastructure protection, and government cyber budgets.',
    thumbnail: 'https://i.ytimg.com/vi/fN1Cyr0ZK9M/hqdefault.jpg',
    channelTitle: 'Cyber Security Policy',
    duration: '26:30',
    tags: ['Defense Tech', 'Cyber Warfare', 'Security'],
  },
  {
    youtubeVideoId: 'kUMe1FH4CHE',
    title: 'Open Source Software Economic Impact & Sustainability',
    category: 'Current Affairs',
    description: 'Funding open-source maintainers, security vulnerabilities in supply chains, and enterprise sponsorship.',
    thumbnail: 'https://i.ytimg.com/vi/kUMe1FH4CHE/hqdefault.jpg',
    channelTitle: 'Open Source Today',
    duration: '18:10',
    tags: ['Open Source', 'Community', 'Software'],
  },
  {
    youtubeVideoId: 'N3AkSS5hXMA',
    title: 'The State of Tech Diversity & Inclusion Hiring Initiatives',
    category: 'Current Affairs',
    description: 'Progress, benchmarks, and strategies for fostering inclusive software engineering teams.',
    thumbnail: 'https://i.ytimg.com/vi/N3AkSS5hXMA/hqdefault.jpg',
    channelTitle: 'Inclusive Tech Hub',
    duration: '15:45',
    tags: ['Diversity', 'Inclusion', 'Culture'],
  },

  // ── 2. TECHNOLOGY (15 videos) ────────────────────────────────────────────────
  {
    youtubeVideoId: 'w7ejDZ8SWv8',
    title: 'Modern Cloud Architecture: AWS, Azure & GCP Systems',
    category: 'Technology',
    description: 'Deep dive into cloud native infrastructure, serverless computing, and multi-cloud strategies.',
    thumbnail: 'https://i.ytimg.com/vi/w7ejDZ8SWv8/hqdefault.jpg',
    channelTitle: 'TechWorld with Nana',
    duration: '32:00',
    tags: ['Cloud', 'AWS', 'Kubernetes', 'Architecture'],
  },
  {
    youtubeVideoId: '8jLOx1hD3_o',
    title: 'Docker & Kubernetes Mastery in 2025',
    category: 'Technology',
    description: 'Master containerization, orchestration, ingress controllers, and microservices deployment.',
    thumbnail: 'https://i.ytimg.com/vi/8jLOx1hD3_o/hqdefault.jpg',
    channelTitle: 'DevOps Directive',
    duration: '45:10',
    tags: ['Docker', 'Kubernetes', 'DevOps'],
  },
  {
    youtubeVideoId: '30LWjhZzg50',
    title: 'System Design Fundamentals for Scalable Applications',
    category: 'Technology',
    description: 'Load balancers, database sharding, caching strategies, and message queues explained clearly.',
    thumbnail: 'https://i.ytimg.com/vi/30LWjhZzg50/hqdefault.jpg',
    channelTitle: 'ByteByteGo',
    duration: '29:40',
    tags: ['System Design', 'Scalability', 'Architecture'],
  },
  {
    youtubeVideoId: 'rfscVS0vtbw',
    title: 'Python for Technology Solutions & Automation',
    category: 'Technology',
    description: 'Build backend APIs, web scrapers, data pipelines, and automation bots using modern Python 3.12.',
    thumbnail: 'https://i.ytimg.com/vi/rfscVS0vtbw/hqdefault.jpg',
    channelTitle: 'FreeCodeCamp',
    duration: '55:00',
    tags: ['Python', 'Automation', 'APIs'],
  },
  {
    youtubeVideoId: 'HgtRAbE1nBM',
    title: '5G, 6G & Edge Computing Networking Protocols',
    category: 'Technology',
    description: 'Understanding low latency edge nodes, IoT sensors, and next-generation telecommunications.',
    thumbnail: 'https://i.ytimg.com/vi/HgtRAbE1nBM/hqdefault.jpg',
    channelTitle: 'NetworkChuck',
    duration: '23:15',
    tags: ['Networking', '5G', 'Edge Computing'],
  },
  {
    youtubeVideoId: 'gAkwW2tuIqE',
    title: 'WebAssembly (Wasm) & High-Performance Browser Tech',
    category: 'Technology',
    description: 'Running C++, Rust, and Go inside web browsers at native execution speeds.',
    thumbnail: 'https://i.ytimg.com/vi/gAkwW2tuIqE/hqdefault.jpg',
    channelTitle: 'Fireship',
    duration: '12:30',
    tags: ['WebAssembly', 'Rust', 'Performance'],
  },
  {
    youtubeVideoId: 'Oe421EPjeBE',
    title: 'GraphQL vs REST vs gRPC API Technologies',
    category: 'Technology',
    description: 'Choosing the right communication protocol for microservices, mobile apps, and enterprise APIs.',
    thumbnail: 'https://i.ytimg.com/vi/Oe421EPjeBE/hqdefault.jpg',
    channelTitle: 'Hussein Nasser',
    duration: '31:00',
    tags: ['APIs', 'GraphQL', 'gRPC', 'Backend'],
  },
  {
    youtubeVideoId: 'VqCgcpAEdqc',
    title: 'Database Technologies: SQL vs NoSQL vs Vector DBs',
    category: 'Technology',
    description: 'PostgreSQL, MongoDB, Redis, and Pinecone vector databases comparison for modern apps.',
    thumbnail: 'https://i.ytimg.com/vi/VqCgcpAEdqc/hqdefault.jpg',
    channelTitle: 'Database Weekly',
    duration: '27:45',
    tags: ['Database', 'PostgreSQL', 'MongoDB', 'VectorDB'],
  },
  {
    youtubeVideoId: '7E6bIvwL6vI',
    title: 'Linux Command Line & System Administration Masterclass',
    category: 'Technology',
    description: 'Essential bash scripts, user permission management, networking commands, and server maintenance.',
    thumbnail: 'https://i.ytimg.com/vi/7E6bIvwL6vI/hqdefault.jpg',
    channelTitle: 'Learn Linux TV',
    duration: '40:20',
    tags: ['Linux', 'SysAdmin', 'Bash'],
  },
  {
    youtubeVideoId: 'QeFDW3M3Y0g',
    title: 'Blockchain & Decentralized Tech Protocols 2025',
    category: 'Technology',
    description: 'Smart contracts, Ethereum EVM development, zero-knowledge proofs, and Web3 infrastructure.',
    thumbnail: 'https://i.ytimg.com/vi/QeFDW3M3Y0g/hqdefault.jpg',
    channelTitle: 'Dapp University',
    duration: '34:10',
    tags: ['Web3', 'Blockchain', 'Smart Contracts'],
  },
  {
    youtubeVideoId: 'K5KAc5meDAg',
    title: 'Serverless Tech Architecture: AWS Lambda & Cloudflare Workers',
    category: 'Technology',
    description: 'Building event-driven cost-effective serverless backend applications.',
    thumbnail: 'https://i.ytimg.com/vi/K5KAc5meDAg/hqdefault.jpg',
    channelTitle: 'Serverless Crafter',
    duration: '21:50',
    tags: ['Serverless', 'AWS Lambda', 'Cloudflare'],
  },
  {
    youtubeVideoId: 'S-7m_yO1x_U',
    title: 'Infrastructure as Code with Terraform & Pulumi',
    category: 'Technology',
    description: 'Automate multi-cloud provisioning using declarative configuration files.',
    thumbnail: 'https://i.ytimg.com/vi/S-7m_yO1x_U/hqdefault.jpg',
    channelTitle: 'DevOps Toolkit',
    duration: '26:00',
    tags: ['Terraform', 'IaC', 'DevOps'],
  },
  {
    youtubeVideoId: 'a2Z6b3b24fE',
    title: 'Micro Frontends & Scalable Web Architecture',
    category: 'Technology',
    description: 'Splitting large web applications into independently deployable frontend modules.',
    thumbnail: 'https://i.ytimg.com/vi/a2Z6b3b24fE/hqdefault.jpg',
    channelTitle: 'Frontend Masters',
    duration: '24:15',
    tags: ['Frontend', 'Micro Frontends', 'Architecture'],
  },
  {
    youtubeVideoId: 'N170D48dG28',
    title: 'CI/CD Automated Testing & Deployment Pipelines',
    category: 'Technology',
    description: 'GitHub Actions, GitLab CI, and automated regression testing workflows.',
    thumbnail: 'https://i.ytimg.com/vi/N170D48dG28/hqdefault.jpg',
    channelTitle: 'Automation Tech',
    duration: '22:30',
    tags: ['CI/CD', 'GitHub Actions', 'Testing'],
  },
  {
    youtubeVideoId: 'D8bH_rG4O3s',
    title: 'Spatial Computing & AR/VR Hardware Technology',
    category: 'Technology',
    description: 'VisionOS, Unity 3D engine, and spatial UI development for immersive headsets.',
    thumbnail: 'https://i.ytimg.com/vi/D8bH_rG4O3s/hqdefault.jpg',
    channelTitle: 'Spatial Tech Lab',
    duration: '30:00',
    tags: ['AR', 'VR', 'Spatial Computing'],
  },

  // ── 3. SOFTWARE DEVELOPMENT (15 videos) ────────────────────────────────────
  {
    youtubeVideoId: 'PkZNo7MFNFg',
    title: 'Full Stack Web Development Complete Bootcamp (MERN)',
    category: 'Software Development',
    description: 'Build production-ready React, Node.js, Express, and MongoDB web applications from scratch.',
    thumbnail: 'https://i.ytimg.com/vi/PkZNo7MFNFg/hqdefault.jpg',
    channelTitle: 'Traversy Media',
    duration: '48:00',
    tags: ['React', 'Node.js', 'MERN', 'JavaScript'],
  },
  {
    youtubeVideoId: 'bMknfKXIFA8',
    title: 'React 19 & Next.js 15 Full Course: Server Components & App Router',
    category: 'Software Development',
    description: 'Master React server components, server actions, dynamic routing, and SSR caching.',
    thumbnail: 'https://i.ytimg.com/vi/bMknfKXIFA8/hqdefault.jpg',
    channelTitle: 'JavaScript Mastery',
    duration: '52:10',
    tags: ['React', 'Next.js', 'Frontend', 'TypeScript'],
  },
  {
    youtubeVideoId: '1rsJgLDdeBU',
    title: 'Data Structures & Algorithms Course for Software Interviews',
    category: 'Software Development',
    description: 'Arrays, Trees, Graphs, Dynamic Programming, and Big-O Time Complexity in Python & JS.',
    thumbnail: 'https://i.ytimg.com/vi/1rsJgLDdeBU/hqdefault.jpg',
    channelTitle: 'NeetCode',
    duration: '1:10:00',
    tags: ['Algorithms', 'Data Structures', 'LeetCode', 'Interviews'],
  },
  {
    youtubeVideoId: '8aGhZQkoFbQ',
    title: 'TypeScript for Professional Developers (Zero to Master)',
    category: 'Software Development',
    description: 'Generics, utility types, type guards, interfaces, and strict type checking patterns.',
    thumbnail: 'https://i.ytimg.com/vi/8aGhZQkoFbQ/hqdefault.jpg',
    channelTitle: 'Jack Herrington',
    duration: '38:40',
    tags: ['TypeScript', 'JavaScript', 'Frontend'],
  },
  {
    youtubeVideoId: 'gB1F9G0JXOo',
    title: 'Clean Code & Refactoring Best Practices',
    category: 'Software Development',
    description: 'SOLID principles, DRY, design patterns, readable naming conventions, and modular code.',
    thumbnail: 'https://i.ytimg.com/vi/gB1F9G0JXOo/hqdefault.jpg',
    channelTitle: 'CodeAesthetic',
    duration: '16:50',
    tags: ['Clean Code', 'Design Patterns', 'Refactoring'],
  },
  {
    youtubeVideoId: 'SqcY0GlETPk',
    title: 'Git & GitHub Collaboration Workflow for Dev Teams',
    category: 'Software Development',
    description: 'Branching strategies, PR reviews, rebase vs merge, resolve merge conflicts like a pro.',
    thumbnail: 'https://i.ytimg.com/vi/SqcY0GlETPk/hqdefault.jpg',
    channelTitle: 'Corey Schafer',
    duration: '27:30',
    tags: ['Git', 'GitHub', 'Version Control'],
  },
  {
    youtubeVideoId: 'fN1Cyr0ZK9M',
    title: 'Building RESTful APIs with Node.js & Express',
    category: 'Software Development',
    description: 'JWT authentication, middleware, rate limiting, error handling, and MongoDB Mongoose models.',
    thumbnail: 'https://i.ytimg.com/vi/fN1Cyr0ZK9M/hqdefault.jpg',
    channelTitle: 'Web Dev Simplified',
    duration: '35:20',
    tags: ['Node.js', 'Express', 'Backend', 'APIs'],
  },
  {
    youtubeVideoId: 'kUMe1FH4CHE',
    title: 'Python Django & FastAPI Web Development Guide',
    category: 'Software Development',
    description: 'High-performance asynchronous Python web APIs using FastAPI and Pydantic validation.',
    thumbnail: 'https://i.ytimg.com/vi/kUMe1FH4CHE/hqdefault.jpg',
    channelTitle: 'ArjanCodes',
    duration: '33:45',
    tags: ['Python', 'FastAPI', 'Django', 'Backend'],
  },
  {
    youtubeVideoId: 'N3AkSS5hXMA',
    title: 'Android & iOS Cross-Platform Mobile App Dev (React Native)',
    category: 'Software Development',
    description: 'Build native iOS and Android apps using React Native, Expo, and Tailwind styling.',
    thumbnail: 'https://i.ytimg.com/vi/N3AkSS5hXMA/hqdefault.jpg',
    channelTitle: 'Sonny Sangha',
    duration: '42:15',
    tags: ['React Native', 'Mobile Apps', 'Expo'],
  },
  {
    youtubeVideoId: 'w7ejDZ8SWv8',
    title: 'Flutter & Dart Mobile App Development Masterclass',
    category: 'Software Development',
    description: 'State management, Riverpod, custom UI animations, and native device feature integration.',
    thumbnail: 'https://i.ytimg.com/vi/w7ejDZ8SWv8/hqdefault.jpg',
    channelTitle: 'Flutter Mapp',
    duration: '39:00',
    tags: ['Flutter', 'Dart', 'Mobile'],
  },
  {
    youtubeVideoId: '8jLOx1hD3_o',
    title: 'Rust Programming Language Complete Beginner Course',
    category: 'Software Development',
    description: 'Memory safety without garbage collection: ownership, borrowing, lifetimes, and cargo.',
    thumbnail: 'https://i.ytimg.com/vi/8jLOx1hD3_o/hqdefault.jpg',
    channelTitle: 'No Boilerplate',
    duration: '31:10',
    tags: ['Rust', 'Systems Programming', 'Performance'],
  },
  {
    youtubeVideoId: '30LWjhZzg50',
    title: 'Go (Golang) Microservices & Concurrent Backend APIs',
    category: 'Software Development',
    description: 'Goroutines, channels, gRPC, and building ultra-fast backend microservices in Go.',
    thumbnail: 'https://i.ytimg.com/vi/30LWjhZzg50/hqdefault.jpg',
    channelTitle: 'Golang University',
    duration: '36:20',
    tags: ['Go', 'Golang', 'Microservices'],
  },
  {
    youtubeVideoId: 'rfscVS0vtbw',
    title: 'Automated Testing with Jest, Vitest & Playwright',
    category: 'Software Development',
    description: 'Unit testing, integration testing, component testing, and end-to-end (E2E) browser tests.',
    thumbnail: 'https://i.ytimg.com/vi/rfscVS0vtbw/hqdefault.jpg',
    channelTitle: 'Testing Academy',
    duration: '28:50',
    tags: ['Jest', 'Playwright', 'Testing', 'QA'],
  },
  {
    youtubeVideoId: 'HgtRAbE1nBM',
    title: 'Tailwind CSS v4 & Modern Web Component Styling',
    category: 'Software Development',
    description: 'Utility-first CSS, dark mode design systems, custom themes, and glassmorphism styling.',
    thumbnail: 'https://i.ytimg.com/vi/HgtRAbE1nBM/hqdefault.jpg',
    channelTitle: 'Tailwind Labs',
    duration: '23:40',
    tags: ['CSS', 'Tailwind', 'UI Styling'],
  },
  {
    youtubeVideoId: 'gAkwW2tuIqE',
    title: 'Software Architect Roadmap: From Senior Engineer to Tech Lead',
    category: 'Software Development',
    description: 'Technical leadership, domain-driven design (DDD), trade-off evaluation, and architecture specs.',
    thumbnail: 'https://i.ytimg.com/vi/gAkwW2tuIqE/hqdefault.jpg',
    channelTitle: 'Tech Lead Journal',
    duration: '37:15',
    tags: ['Software Architect', 'Leadership', 'Career Growth'],
  },

  // ── 4. CYBERSECURITY (15 videos) ────────────────────────────────────────────
  {
    youtubeVideoId: '0GypdsJQN4',
    title: 'Cybersecurity Full Roadmap 2025: From Beginner to Ethical Hacker',
    category: 'Cybersecurity',
    description: 'Comprehensive pathway into cybersecurity: certifications, lab setups, networking, and career advice.',
    thumbnail: 'https://i.ytimg.com/vi/0GypdsJQN4/hqdefault.jpg',
    channelTitle: 'NetworkChuck',
    duration: '31:20',
    tags: ['Cybersecurity', 'Ethical Hacking', 'CompTIA', 'Roadmap'],
  },
  {
    youtubeVideoId: '3Kq1MIfTWCE',
    title: 'OWASP Top 10 Web Vulnerabilities & Penetration Testing',
    category: 'Cybersecurity',
    description: 'SQL injection, Cross-Site Scripting (XSS), CSRF, broken authentication, and patch methods.',
    thumbnail: 'https://i.ytimg.com/vi/3Kq1MIfTWCE/hqdefault.jpg',
    channelTitle: 'The Cyber Mentor',
    duration: '42:30',
    tags: ['OWASP', 'Penetration Testing', 'Web Security'],
  },
  {
    youtubeVideoId: 'qwA6MmjsGNo',
    title: 'Network Security Fundamentals & Wireshark Packet Analysis',
    category: 'Cybersecurity',
    description: 'TCP/IP handshake, DNS spoofing, firewall rule configuration, and deep packet analysis.',
    thumbnail: 'https://i.ytimg.com/vi/qwA6MmjsGNo/hqdefault.jpg',
    channelTitle: 'David Bombal',
    duration: '36:15',
    tags: ['Networking', 'Wireshark', 'Packet Analysis'],
  },
  {
    youtubeVideoId: 'inWWhr5tnEA',
    title: 'CompTIA Security+ SY0-701 Full Exam Prep Course',
    category: 'Cybersecurity',
    description: 'Master all security domains required to pass the industry-standard Security+ credential.',
    thumbnail: 'https://i.ytimg.com/vi/inWWhr5tnEA/hqdefault.jpg',
    channelTitle: 'Professor Messer',
    duration: '1:05:00',
    tags: ['Security+', 'CompTIA', 'Certifications'],
  },
  {
    youtubeVideoId: 'bPVaOlJ6ln0',
    title: 'SOC Analyst Fundamentals: Incident Response & SIEM Tools',
    category: 'Cybersecurity',
    description: 'Splunk, Elastic SIEM, threat hunting workflows, and analyzing malware logs in a Security Operations Center.',
    thumbnail: 'https://i.ytimg.com/vi/bPVaOlJ6ln0/hqdefault.jpg',
    channelTitle: 'Gerald Augur',
    duration: '29:40',
    tags: ['SOC Analyst', 'SIEM', 'Splunk', 'Incident Response'],
  },
  {
    youtubeVideoId: 'lZAoFs75_cs',
    title: 'Cloud Security Architecture on AWS & Azure (Zero Trust)',
    category: 'Cybersecurity',
    description: 'IAM least privilege, VPC security groups, KMS encryption, and Zero Trust security principles.',
    thumbnail: 'https://i.ytimg.com/vi/lZAoFs75_cs/hqdefault.jpg',
    channelTitle: 'Cloud Security Academy',
    duration: '34:20',
    tags: ['Cloud Security', 'AWS Security', 'Zero Trust'],
  },
  {
    youtubeVideoId: '2b3ptqxs1_I',
    title: 'Python for Ethical Hackers & Security Automation',
    category: 'Cybersecurity',
    description: 'Write custom port scanners, sub-domain brute forcers, payload generators, and exploit scripts.',
    thumbnail: 'https://i.ytimg.com/vi/2b3ptqxs1_I/hqdefault.jpg',
    channelTitle: 'FreeCodeCamp Security',
    duration: '40:10',
    tags: ['Python Security', 'Automation', 'Ethical Hacking'],
  },
  {
    youtubeVideoId: 'W3q8Od5qJio',
    title: 'Malware Analysis & Reverse Engineering Basics',
    category: 'Cybersecurity',
    description: 'Disassembling binaries with Ghidra, sandbox analysis, assembly language basics, and ransomware analysis.',
    thumbnail: 'https://i.ytimg.com/vi/W3q8Od5qJio/hqdefault.jpg',
    channelTitle: 'HuskyHacks',
    duration: '38:50',
    tags: ['Malware Analysis', 'Reverse Engineering', 'Ghidra'],
  },
  {
    youtubeVideoId: 'Oe421EPjeBE',
    title: 'Bug Bounty Hunting: How to Find Vulnerabilities & Earn Bounties',
    category: 'Cybersecurity',
    description: 'HackerOne and Bugcrowd strategies, recon tools, sub-domain enumeration, and report writing.',
    thumbnail: 'https://i.ytimg.com/vi/Oe421EPjeBE/hqdefault.jpg',
    channelTitle: 'NahamSec',
    duration: '27:00',
    tags: ['Bug Bounty', 'HackerOne', 'Recon'],
  },
  {
    youtubeVideoId: 'VqCgcpAEdqc',
    title: 'Cryptography Fundamentals: Public Key Encryption & Hashing',
    category: 'Cybersecurity',
    description: 'AES-256, RSA, ECC, SHA-256, TLS 1.3 certificates, and key management systems.',
    thumbnail: 'https://i.ytimg.com/vi/VqCgcpAEdqc/hqdefault.jpg',
    channelTitle: 'Computerphile',
    duration: '21:30',
    tags: ['Cryptography', 'Encryption', 'TLS'],
  },
  {
    youtubeVideoId: '7E6bIvwL6vI',
    title: 'Active Directory Hacking & Enterprise Domain Defense',
    category: 'Cybersecurity',
    description: 'Kerberoasting, BloodHound, Pass-the-Hash attacks, and securing Active Directory domain controllers.',
    thumbnail: 'https://i.ytimg.com/vi/7E6bIvwL6vI/hqdefault.jpg',
    channelTitle: 'IppSec',
    duration: '44:00',
    tags: ['Active Directory', 'Red Team', 'Kerberos'],
  },
  {
    youtubeVideoId: 'QeFDW3M3Y0g',
    title: 'Certified Ethical Hacker (CEH) vs Security+ vs CISSP',
    category: 'Cybersecurity',
    description: 'Comparison of cybersecurity certification pathways, salaries, and prerequisite requirements.',
    thumbnail: 'https://i.ytimg.com/vi/QeFDW3M3Y0g/hqdefault.jpg',
    channelTitle: 'Cyber Insecurity',
    duration: '19:40',
    tags: ['Certifications', 'CISSP', 'Career Guidance'],
  },
  {
    youtubeVideoId: 'K5KAc5meDAg',
    title: 'API Security & Securing Microservices Infrastructure',
    category: 'Cybersecurity',
    description: 'OAuth 2.0, OpenID Connect, rate limiting, CORS policies, and API gateway security.',
    thumbnail: 'https://i.ytimg.com/vi/K5KAc5meDAg/hqdefault.jpg',
    channelTitle: 'API Security Hub',
    duration: '25:15',
    tags: ['API Security', 'OAuth', 'Microservices'],
  },
  {
    youtubeVideoId: 'S-7m_yO1x_U',
    title: 'DevSecOps: Integrating Security into CI/CD Pipelines',
    category: 'Cybersecurity',
    description: 'Static Application Security Testing (SAST), DAST, dependency scanning with Snyk, and container auditing.',
    thumbnail: 'https://i.ytimg.com/vi/S-7m_yO1x_U/hqdefault.jpg',
    channelTitle: 'DevSecOps World',
    duration: '30:45',
    tags: ['DevSecOps', 'SAST', 'Snyk', 'CI/CD'],
  },
  {
    youtubeVideoId: 'a2Z6b3b24fE',
    title: 'Digital Forensics & Incident Investigation (DFIR)',
    category: 'Cybersecurity',
    description: 'Memory dump analysis with Volatility, disk forensics, chain of custody, and forensic reporting.',
    thumbnail: 'https://i.ytimg.com/vi/a2Z6b3b24fE/hqdefault.jpg',
    channelTitle: '13Cube Forensics',
    duration: '33:10',
    tags: ['DFIR', 'Digital Forensics', 'Incident Response'],
  },

  // ── 5. GRAPHIC DESIGN (15 videos) ──────────────────────────────────────────
  {
    youtubeVideoId: 'vLsVkgngKDQ',
    title: 'UI/UX Design Full Career Roadmap: From Beginner to Senior Designer',
    category: 'Graphic Design',
    description: 'Step-by-step masterclass on design principles, Figma prototyping, user research, and portfolio crafting.',
    thumbnail: 'https://i.ytimg.com/vi/vLsVkgngKDQ/hqdefault.jpg',
    channelTitle: 'DesignCourse',
    duration: '28:10',
    tags: ['UI UX', 'Figma', 'Graphic Design', 'Portfolio'],
  },
  {
    youtubeVideoId: 'c9Wg6Cb_YlU',
    title: 'Figma Auto-Layout & Design System Masterclass',
    category: 'Graphic Design',
    description: 'Master dynamic auto-layout, design tokens, color variables, variants, and component libraries.',
    thumbnail: 'https://i.ytimg.com/vi/c9Wg6Cb_YlU/hqdefault.jpg',
    channelTitle: 'Mizko',
    duration: '35:40',
    tags: ['Figma', 'Design Systems', 'Auto Layout'],
  },
  {
    youtubeVideoId: 'YqQx75OPRa0',
    title: 'Graphic Design Principles: Typography, Color Theory & Grid Systems',
    category: 'Graphic Design',
    description: 'Fundamental visual composition rules, font pairing secrets, contrast ratios, and whitespace mastery.',
    thumbnail: 'https://i.ytimg.com/vi/YqQx75OPRa0/hqdefault.jpg',
    channelTitle: 'The Futur',
    duration: '24:30',
    tags: ['Typography', 'Color Theory', 'Layout', 'Visual Design'],
  },
  {
    youtubeVideoId: 'zU9p0J0B1f0',
    title: 'Adobe Illustrator & Vector Art Masterclass for Beginners',
    category: 'Graphic Design',
    description: 'Pen tool techniques, shape builder, logo design workflow, and vector brand assets creation.',
    thumbnail: 'https://i.ytimg.com/vi/zU9p0J0B1f0/hqdefault.jpg',
    channelTitle: 'Satori Graphics',
    duration: '40:00',
    tags: ['Adobe Illustrator', 'Logo Design', 'Vector Art'],
  },
  {
    youtubeVideoId: 'Jg7s_pW2o8k',
    title: 'Adobe Photoshop for Graphic Designers & Photo Compositing',
    category: 'Graphic Design',
    description: 'Layer masks, smart objects, color grading, photo manipulation, and poster typography design.',
    thumbnail: 'https://i.ytimg.com/vi/Jg7s_pW2o8k/hqdefault.jpg',
    channelTitle: 'Phlearn',
    duration: '38:15',
    tags: ['Photoshop', 'Photo Editing', 'Compositing'],
  },
  {
    youtubeVideoId: 'bJzb-RuUcMU',
    title: 'Brand Identity Design: How to Build a $10,000 Brand Package',
    category: 'Graphic Design',
    description: 'Logo mark design, brand guidelines document, typography hierarchy, and mockups presentation.',
    thumbnail: 'https://i.ytimg.com/vi/bJzb-RuUcMU/hqdefault.jpg',
    channelTitle: 'Will Paterson',
    duration: '29:50',
    tags: ['Branding', 'Brand Identity', 'Logo Design'],
  },
  {
    youtubeVideoId: 'SqcY0GlETPk',
    title: 'Motion Design & 2D Animation in Adobe After Effects',
    category: 'Graphic Design',
    description: 'Keyframe easing, shape layer animation, UI motion design, and logo reveal animation.',
    thumbnail: 'https://i.ytimg.com/vi/SqcY0GlETPk/hqdefault.jpg',
    channelTitle: 'School of Motion',
    duration: '32:10',
    tags: ['After Effects', 'Motion Design', 'Animation'],
  },
  {
    youtubeVideoId: 'fN1Cyr0ZK9M',
    title: 'User Experience (UX) Research Methods & Usability Testing',
    category: 'Graphic Design',
    description: 'User interviews, card sorting, journey mapping, wireframing, and interactive prototype testing.',
    thumbnail: 'https://i.ytimg.com/vi/fN1Cyr0ZK9M/hqdefault.jpg',
    channelTitle: 'NNgroup UX',
    duration: '26:40',
    tags: ['UX Research', 'Usability Testing', 'Wireframing'],
  },
  {
    youtubeVideoId: 'kUMe1FH4CHE',
    title: 'Design Portfolio Review: What Top Tech Agencies Look For',
    category: 'Graphic Design',
    description: 'Case study structure, problem statement framing, UI screenshots, and landing portfolio presentation.',
    thumbnail: 'https://i.ytimg.com/vi/kUMe1FH4CHE/hqdefault.jpg',
    channelTitle: 'Femke Design',
    duration: '22:00',
    tags: ['Portfolio', 'Design Review', 'Career Advice'],
  },
  {
    youtubeVideoId: 'N3AkSS5hXMA',
    title: '3D UI Graphics & Blender Product Rendering Basics',
    category: 'Graphic Design',
    description: 'Creating 3D icons, glassmorphism materials, lighting setups, and exporting 3D web assets.',
    thumbnail: 'https://i.ytimg.com/vi/N3AkSS5hXMA/hqdefault.jpg',
    channelTitle: 'Blender Guru',
    duration: '45:00',
    tags: ['3D Design', 'Blender', 'UI Icons'],
  },
  {
    youtubeVideoId: 'w7ejDZ8SWv8',
    title: 'Web Design Layouts: Figma to Framer Web Development',
    category: 'Graphic Design',
    description: 'Transforming Figma web designs into interactive animated Framer websites.',
    thumbnail: 'https://i.ytimg.com/vi/w7ejDZ8SWv8/hqdefault.jpg',
    channelTitle: 'Framer Academy',
    duration: '31:25',
    tags: ['Framer', 'Web Design', 'No Code'],
  },
  {
    youtubeVideoId: '8jLOx1hD3_o',
    title: 'Accessibility (a11y) in UI Design & WCAG Guidelines',
    category: 'Graphic Design',
    description: 'Color contrast checkers, screen reader compatibility, accessible focus states, and typography scalability.',
    thumbnail: 'https://i.ytimg.com/vi/8jLOx1hD3_o/hqdefault.jpg',
    channelTitle: 'Accessibility UX',
    duration: '20:10',
    tags: ['Accessibility', 'a11y', 'WCAG'],
  },
  {
    youtubeVideoId: '30LWjhZzg50',
    title: 'Design Systems Architecture for Enterprise Products',
    category: 'Graphic Design',
    description: 'Managing design components at scale across multi-platform web, iOS, and Android products.',
    thumbnail: 'https://i.ytimg.com/vi/30LWjhZzg50/hqdefault.jpg',
    channelTitle: 'Design Systems Daily',
    duration: '27:40',
    tags: ['Design Systems', 'Enterprise UI', 'Components'],
  },
  {
    youtubeVideoId: 'rfscVS0vtbw',
    title: 'Freelance Graphic Design Business: Pricing, Clients & Contracts',
    category: 'Graphic Design',
    description: 'How to price design services, pitch proposals, write client contracts, and generate recurring leads.',
    thumbnail: 'https://i.ytimg.com/vi/rfscVS0vtbw/hqdefault.jpg',
    channelTitle: 'Flux Academy',
    duration: '34:00',
    tags: ['Freelancing', 'Design Business', 'Pricing'],
  },
  {
    youtubeVideoId: 'HgtRAbE1nBM',
    title: 'Generative AI Tools for Graphic Designers (Midjourney & Firefly)',
    category: 'Graphic Design',
    description: 'Integrating AI image generation, vector AI, and Photoshop Generative Fill into visual design workflows.',
    thumbnail: 'https://i.ytimg.com/vi/HgtRAbE1nBM/hqdefault.jpg',
    channelTitle: 'AI Design World',
    duration: '23:50',
    tags: ['Generative AI', 'Midjourney', 'Photoshop AI'],
  },

  // ── 6. AI & MACHINE LEARNING (15 videos) ────────────────────────────────────
  {
    youtubeVideoId: 'ua-CiDNNj30',
    title: 'Data Science & Machine Learning Complete Career Guide',
    category: 'AI & Machine Learning',
    description: 'Comprehensive roadmap to becoming an AI Engineer, Data Scientist, or ML Researcher in 2025.',
    thumbnail: 'https://i.ytimg.com/vi/ua-CiDNNj30/hqdefault.jpg',
    channelTitle: 'Ken Jee',
    duration: '35:40',
    tags: ['Data Science', 'Machine Learning', 'AI Engineer', 'Python'],
  },
  {
    youtubeVideoId: 'aircAruvnKk',
    title: 'Neural Networks & Deep Learning from Scratch with PyTorch',
    category: 'AI & Machine Learning',
    description: 'Understand backpropagation, gradient descent, activation functions, and building PyTorch models.',
    thumbnail: 'https://i.ytimg.com/vi/aircAruvnKk/hqdefault.jpg',
    channelTitle: '3Blue1Brown',
    duration: '48:20',
    tags: ['Deep Learning', 'PyTorch', 'Neural Networks', 'Math'],
  },
  {
    youtubeVideoId: 'VMj-3lSmWrY',
    title: 'Large Language Models (LLMs) Architecture: Transformers Explained',
    category: 'AI & Machine Learning',
    description: 'How GPT-4, Llama 3, and Claude work: self-attention mechanisms, tokenization, and embeddings.',
    thumbnail: 'https://i.ytimg.com/vi/VMj-3lSmWrY/hqdefault.jpg',
    channelTitle: 'Andrej Karpathy',
    duration: '1:15:00',
    tags: ['LLM', 'Transformers', 'Generative AI', 'NLP'],
  },
  {
    youtubeVideoId: 'zjkBMFhNj_g',
    title: 'Building RAG (Retrieval-Augmented Generation) Apps with LangChain',
    category: 'AI & Machine Learning',
    description: 'Connect LLMs to custom enterprise data using vector databases (Pinecone, ChromaDB) and LangChain.',
    thumbnail: 'https://i.ytimg.com/vi/zjkBMFhNj_g/hqdefault.jpg',
    channelTitle: 'Harrison Chase / LangChain',
    duration: '41:10',
    tags: ['RAG', 'LangChain', 'VectorDB', 'Python AI'],
  },
  {
    youtubeVideoId: 'QeFDW3M3Y0g',
    title: 'Machine Learning Engineering & MLOps Pipelines',
    category: 'AI & Machine Learning',
    description: 'Model deployment, MLflow tracking, Docker containers for AI, model monitoring, and feature stores.',
    thumbnail: 'https://i.ytimg.com/vi/QeFDW3M3Y0g/hqdefault.jpg',
    channelTitle: 'MLOps World',
    duration: '36:45',
    tags: ['MLOps', 'MLflow', 'Model Deployment'],
  },
  {
    youtubeVideoId: 'K5KAc5meDAg',
    title: 'Python Pandas, NumPy & Data Visualization Masterclass',
    category: 'AI & Machine Learning',
    description: 'Data cleaning, feature engineering, Matplotlib plots, Seaborn statistical graphics, and Exploratory Data Analysis (EDA).',
    thumbnail: 'https://i.ytimg.com/vi/K5KAc5meDAg/hqdefault.jpg',
    channelTitle: 'Keith Galli',
    duration: '50:00',
    tags: ['Pandas', 'NumPy', 'Data Analysis', 'EDA'],
  },
  {
    youtubeVideoId: 'S-7m_yO1x_U',
    title: 'Computer Vision & OpenCV Image Processing with Python',
    category: 'AI & Machine Learning',
    description: 'YOLO object detection, facial recognition, image segmentation, and real-time video stream processing.',
    thumbnail: 'https://i.ytimg.com/vi/S-7m_yO1x_U/hqdefault.jpg',
    channelTitle: 'Murtaza\'s Workshop',
    duration: '44:15',
    tags: ['Computer Vision', 'OpenCV', 'YOLO', 'AI'],
  },
  {
    youtubeVideoId: 'a2Z6b3b24fE',
    title: 'Fine-Tuning LLMs with LoRA, QLoRA & Hugging Face Transformers',
    category: 'AI & Machine Learning',
    description: 'Customize open-source AI models on custom domain datasets using parameter-efficient fine-tuning.',
    thumbnail: 'https://i.ytimg.com/vi/a2Z6b3b24fE/hqdefault.jpg',
    channelTitle: 'Hugging Face',
    duration: '37:30',
    tags: ['Fine Tuning', 'LoRA', 'Hugging Face'],
  },
  {
    youtubeVideoId: 'N170D48dG28',
    title: 'Natural Language Processing (NLP) & Sentiment Analysis',
    category: 'AI & Machine Learning',
    description: 'Text preprocessing, TF-IDF, Word2Vec, BERT models, and sentiment classification in Python.',
    thumbnail: 'https://i.ytimg.com/vi/N170D48dG28/hqdefault.jpg',
    channelTitle: 'NLP Specialist',
    duration: '29:10',
    tags: ['NLP', 'BERT', 'Text Analytics'],
  },
  {
    youtubeVideoId: 'D8bH_rG4O3s',
    title: 'Reinforcement Learning & AI Agent Decision Systems',
    category: 'AI & Machine Learning',
    description: 'Q-learning, Deep Q-Networks (DQN), PPO algorithms, and OpenAI Gym simulation environments.',
    thumbnail: 'https://i.ytimg.com/vi/D8bH_rG4O3s/hqdefault.jpg',
    channelTitle: 'RL Lab',
    duration: '42:00',
    tags: ['Reinforcement Learning', 'AI Agents', 'Q-Learning'],
  },
  {
    youtubeVideoId: 'w7ejDZ8SWv8',
    title: 'AI Prompt Engineering & Autonomous Agent Frameworks',
    category: 'AI & Machine Learning',
    description: 'Chain-of-thought prompting, AutoGen, CrewAI, and building autonomous multi-agent software teams.',
    thumbnail: 'https://i.ytimg.com/vi/w7ejDZ8SWv8/hqdefault.jpg',
    channelTitle: 'Prompt Engineer Pro',
    duration: '26:50',
    tags: ['Prompt Engineering', 'CrewAI', 'Agents'],
  },
  {
    youtubeVideoId: '8jLOx1hD3_o',
    title: 'Mathematics for Machine Learning: Linear Algebra & Calculus',
    category: 'AI & Machine Learning',
    description: 'Matrix multiplication, eigenvectors, partial derivatives, and probability distributions for ML.',
    thumbnail: 'https://i.ytimg.com/vi/8jLOx1hD3_o/hqdefault.jpg',
    channelTitle: 'Imperial College London',
    duration: '55:20',
    tags: ['Math for ML', 'Linear Algebra', 'Calculus'],
  },
  {
    youtubeVideoId: '30LWjhZzg50',
    title: 'AI Governance, Safety & Alignment Protocols',
    category: 'AI & Machine Learning',
    description: 'RLHF (Reinforcement Learning from Human Feedback), bias detection, and AI safety benchmarks.',
    thumbnail: 'https://i.ytimg.com/vi/30LWjhZzg50/hqdefault.jpg',
    channelTitle: 'AI Alignment Research',
    duration: '31:40',
    tags: ['AI Safety', 'Alignment', 'Ethics'],
  },
  {
    youtubeVideoId: 'rfscVS0vtbw',
    title: 'Generative AI Art & Diffusion Models (Stable Diffusion)',
    category: 'AI & Machine Learning',
    description: 'Math behind noise latent diffusion, ControlNet, and training custom LoRA weights.',
    thumbnail: 'https://i.ytimg.com/vi/rfscVS0vtbw/hqdefault.jpg',
    channelTitle: 'Generative AI Hub',
    duration: '34:25',
    tags: ['Diffusion Models', 'Stable Diffusion', 'Generative AI'],
  },
  {
    youtubeVideoId: 'HgtRAbE1nBM',
    title: 'SQL for Data Science & Big Data Querying Masterclass',
    category: 'AI & Machine Learning',
    description: 'Window functions, CTEs, subqueries, indexing, and BigQuery analytics for data scientists.',
    thumbnail: 'https://i.ytimg.com/vi/HgtRAbE1nBM/hqdefault.jpg',
    channelTitle: 'Data School',
    duration: '38:10',
    tags: ['SQL', 'BigQuery', 'Data Engineering'],
  },

  // ── 7. JOB MARKET & HIRING TRENDS (15 videos) ──────────────────────────────
  {
    youtubeVideoId: 'J69-q4eLsYU',
    title: 'Top High-Paying Tech Jobs & Salary Benchmarks for 2025',
    category: 'Job Market & Hiring Trends',
    description: 'Detailed analysis of compensation packages, base salaries, stock options, and hiring demand across top tech roles.',
    thumbnail: 'https://i.ytimg.com/vi/J69-q4eLsYU/hqdefault.jpg',
    channelTitle: 'Exponent',
    duration: '18:50',
    tags: ['Job Market', 'Salary Benchmarks', 'Tech Careers', 'Hiring'],
  },
  {
    youtubeVideoId: 'zOjov-2OZ0E',
    title: 'How to Build an ATS-Pass Resume That Gets Technical Interviews',
    category: 'Job Market & Hiring Trends',
    description: 'Applicant Tracking System rules, formatting guidelines, action verbs, and quantitative project metrics.',
    thumbnail: 'https://i.ytimg.com/vi/zOjov-2OZ0E/hqdefault.jpg',
    channelTitle: 'Tech Career Coach',
    duration: '24:15',
    tags: ['Resume Tips', 'ATS', 'Job Search', 'Interviews'],
  },
  {
    youtubeVideoId: 'ua-CiDNNj30',
    title: 'Technical Behavioral Interview STAR Method Blueprint',
    category: 'Job Market & Hiring Trends',
    description: 'How to answer "Tell me about a project", conflict management, and leadership principles at Google & Amazon.',
    thumbnail: 'https://i.ytimg.com/vi/ua-CiDNNj30/hqdefault.jpg',
    channelTitle: 'Interviewing.io',
    duration: '29:00',
    tags: ['Interview Prep', 'STAR Method', 'Behavioral'],
  },
  {
    youtubeVideoId: 'vLsVkgngKDQ',
    title: 'LinkedIn Networking & Cold Outreach System for Jobseekers',
    category: 'Job Market & Hiring Trends',
    description: 'Connecting with recruiters, getting internal referrals, crafting DM templates, and optimizing LinkedIn SEO.',
    thumbnail: 'https://i.ytimg.com/vi/vLsVkgngKDQ/hqdefault.jpg',
    channelTitle: 'CareerVidz',
    duration: '21:40',
    tags: ['LinkedIn', 'Networking', 'Referrals'],
  },
  {
    youtubeVideoId: 'grEKMHGYyns',
    title: 'Negotiating Tech Salary & Equity Compensation Packages',
    category: 'Job Market & Hiring Trends',
    description: 'How to negotiate RSUs, sign-on bonuses, counter-offers, and compensation packages effectively.',
    thumbnail: 'https://i.ytimg.com/vi/grEKMHGYyns/hqdefault.jpg',
    channelTitle: 'Levels.fyi Insights',
    duration: '27:10',
    tags: ['Salary Negotiation', 'Equity', 'RSUs'],
  },
  {
    youtubeVideoId: '0GypdsJQN4',
    title: 'How to Land Remote Software Developer Jobs Globally',
    category: 'Job Market & Hiring Trends',
    description: 'Top job platforms for remote roles, handling international tax compliance, asynchronous communication tests.',
    thumbnail: 'https://i.ytimg.com/vi/0GypdsJQN4/hqdefault.jpg',
    channelTitle: 'Remote Career Hub',
    duration: '25:30',
    tags: ['Remote Jobs', 'Global Hiring', 'Software'],
  },
  {
    youtubeVideoId: 'u72H_4c2dGg',
    title: 'Entry-Level Tech Hiring Realities: How Beginners Win Roles',
    category: 'Job Market & Hiring Trends',
    description: 'Breaking through the "3 years experience required" barrier with open source contributions and portfolio projects.',
    thumbnail: 'https://i.ytimg.com/vi/u72H_4c2dGg/hqdefault.jpg',
    channelTitle: 'Junior Developer Central',
    duration: '23:00',
    tags: ['Junior Roles', 'Entry Level', 'Career Advice'],
  },
  {
    youtubeVideoId: 'X3paOmcrTjQ',
    title: 'Product Management Interview Masterclass (Product Sense & Metrics)',
    category: 'Job Market & Hiring Trends',
    description: 'Answering product design questions, estimation problems, and metric degradation interview scenarios.',
    thumbnail: 'https://i.ytimg.com/vi/X3paOmcrTjQ/hqdefault.jpg',
    channelTitle: 'PM School',
    duration: '36:10',
    tags: ['Product Management', 'PM Interview', 'Metrics'],
  },
  {
    youtubeVideoId: '47d_v6S59C0',
    title: 'System Design Interview Checklist for Senior Engineering Roles',
    category: 'Job Market & Hiring Trends',
    description: 'Structuring a 45-minute system design interview: requirements, API design, data schema, and scaling bottlenecks.',
    thumbnail: 'https://i.ytimg.com/vi/47d_v6S59C0/hqdefault.jpg',
    channelTitle: 'Gaurav Sen',
    duration: '41:00',
    tags: ['System Design', 'Senior Engineer', 'Interviews'],
  },
  {
    youtubeVideoId: 'c9Wg6Cb_YlU',
    title: 'Cybersecurity Interview Questions & Practical Lab Demos',
    category: 'Job Market & Hiring Trends',
    description: 'Technical questions asked in SOC Analyst, Pen Tester, and Cloud Security engineer hiring rounds.',
    thumbnail: 'https://i.ytimg.com/vi/c9Wg6Cb_YlU/hqdefault.jpg',
    channelTitle: 'Cyber Hiring Vault',
    duration: '30:45',
    tags: ['Cybersecurity Interview', 'Technical Interview'],
  },
  {
    youtubeVideoId: 'bJzb-RuUcMU',
    title: 'Data Science Technical Screen: Live Coding & SQL Challenges',
    category: 'Job Market & Hiring Trends',
    description: 'Walkthrough of actual SQL query challenges and Python pandas manipulation tests used by hiring teams.',
    thumbnail: 'https://i.ytimg.com/vi/bJzb-RuUcMU/hqdefault.jpg',
    channelTitle: 'StrataScratch',
    duration: '32:50',
    tags: ['Data Science Interview', 'SQL Challenge', 'Coding'],
  },
  {
    youtubeVideoId: 'SqcY0GlETPk',
    title: 'How Recruiter Sourcing Algorithms Search Candidate Profiles',
    category: 'Job Market & Hiring Trends',
    description: 'Understanding Boolean search strings, LinkedIn Recruiter filters, and how to stay at the top of candidate pools.',
    thumbnail: 'https://i.ytimg.com/vi/SqcY0GlETPk/hqdefault.jpg',
    channelTitle: 'Recruiter Confidential',
    duration: '19:20',
    tags: ['Recruiting', 'Boolean Search', 'Headhunters'],
  },
  {
    youtubeVideoId: 'fN1Cyr0ZK9M',
    title: 'Transitioning from Non-Tech to Software Engineering',
    category: 'Job Market & Hiring Trends',
    description: 'Inspiring career pivot stories, timeline strategies, bootcamp vs self-taught vs degree comparison.',
    thumbnail: 'https://i.ytimg.com/vi/fN1Cyr0ZK9M/hqdefault.jpg',
    channelTitle: 'Career Switcher',
    duration: '28:15',
    tags: ['Career Change', 'Bootcamp', 'Self Taught'],
  },
  {
    youtubeVideoId: 'kUMe1FH4CHE',
    title: 'Freelance & Contract Engineering Market Guide 2025',
    category: 'Job Market & Hiring Trends',
    description: 'Hourly rate benchmarks ($75-$200/hr), finding enterprise clients, platforms like Toptal and Upwork Pro.',
    thumbnail: 'https://i.ytimg.com/vi/kUMe1FH4CHE/hqdefault.jpg',
    channelTitle: 'Contractor Mastery',
    duration: '26:40',
    tags: ['Freelancing', 'Contract Roles', 'Hourly Rates'],
  },
  {
    youtubeVideoId: 'N3AkSS5hXMA',
    title: 'The Role of AI Portfolios in Getting Hired in 2025',
    category: 'Job Market & Hiring Trends',
    description: 'Why static resumes are being replaced by interactive deployed web applications and GitHub portfolios.',
    thumbnail: 'https://i.ytimg.com/vi/N3AkSS5hXMA/hqdefault.jpg',
    channelTitle: 'Portfolio Review Tech',
    duration: '22:30',
    tags: ['Portfolio', 'GitHub', 'Hiring 2025'],
  },
];
